In [1]:
import pandas as pd

In [2]:
# Sterbefälle Bundesländer nach Kalenderwochen - Jahresangaben in Excel Tabellenblatt beachten
sterbefaelle = pd.read_excel("https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/Tabellen/sonderauswertung-sterbefaelle.xlsx?__blob=publicationFile","BL_2016_2021_KW_AG_Ins",skiprows=8)

In [3]:
# Sterbefälle Deutschland nach Kalenderwochen - Jahresangaben in Excel Tabellenblatt beachten
sterbefaelleD = pd.read_excel("https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/Tabellen/sonderauswertung-sterbefaelle.xlsx?__blob=publicationFile","D_2016_2022_KW_AG_Ins",skiprows=8)

In [4]:
sterbefaelleInsgesamt = sterbefaelle[sterbefaelle["unter … Jahren"]=="Insgesamt"]

In [5]:
sterbefaelleDInsgesamt = sterbefaelleD[sterbefaelleD["unter … Jahren"]=="Insgesamt"]

In [6]:
sterbefaelleInsg = sterbefaelleInsgesamt.drop(columns=["unter … Jahren","Nr."]).replace({"Baden-Württemberg" : "BW","Bayern" : "BY","Berlin" : "BE","Brandenburg" : "BB","Bremen" : "HB","Hamburg" : "HH","Hessen" : "HE","Mecklenburg-Vorpommern" : "MV","Niedersachsen" : "NI","Nordrhein-Westfalen" : "NW","Rheinland-Pfalz" : "RP","Saarland" : "SL","Sachsen" : "SN","Sachsen-Anhalt" : "ST","Schleswig-Holstein" : "SH","Thüringen" : "TH"})

In [7]:
sterbefaelleInsg

,Unnamed: 1,Unnamed: 2,1,2,3,4,5,6,7,8,...,44,45,46,47,48,49,50,51,52,53
0,2021,SH,804,794,850,826,778,797,819,677,...,711,705,700,732,770,832,728,786,782,X
5,2021,HH,451,437,463,396,416,363,405,347,...,371,370,378,389,396,400,332,369,400,X
10,2021,NI,2164,2092,2167,2165,2179,2133,2061,1946,...,1931,2049,2142,2081,2163,2187,2113,2055,2117,X
15,2021,HB,181,158,156,148,183,166,165,159,...,150,148,185,175,172,173,166,190,195,X
20,2021,NW,4879,5006,4941,4753,4551,4443,4411,4192,...,4294,4274,4526,4621,5009,4958,4725,4767,4616,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,2016,BB,665,638,649,616,621,659,629,672,...,550,607,563,567,613,627,642,635,637,X
460,2016,MV,487,461,415,434,439,402,441,434,...,387,352,403,374,403,409,420,430,413,X
465,2016,SN,1034,1059,1123,1166,1114,1097,1053,1104,...,993,1079,1084,1037,1030,1118,1158,1137,1219,X
470,2016,ST,658,650,616,601,635,601,627,700,...,552,607,628,598,651,603,629,680,661,X
475,2016,TH,568,551,593,624,617,546,629,611,...,571,550,541,579,614,588,599,618,603,X

In [8]:
sterbefaelleDInsg = sterbefaelleDInsgesamt.drop(columns=["Nr."]).rename(columns={"unter … Jahren": "Unnamed: 2"}).replace({"Insgesamt" : "DE"})

In [9]:
sterbefaelleDInsg

,Unnamed: 1,Unnamed: 2,1,2,3,4,5,6,7,8,...,44,45,46,47,48,49,50,51,52,53
0,2022,DE,20430,19532,19537,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021,DE,24844,24501,24077,22645.0,21736.0,20932.0,20469.0,18950.0,...,20226.0,20930.0,22144.0,23042.0,23968.0,23755.0,22685.0,22272.0,21856.0,X
32,2020,DE,18883,19408,18953,18827.0,19774.0,19038.0,19648.0,18953.0,...,18584.0,19007.0,19727.0,20182.0,21304.0,22604.0,24003.0,24724.0,25554.0,25497
48,2019,DE,18686,19170,19163,19505.0,19812.0,19981.0,20150.0,20349.0,...,17488.0,17859.0,18242.0,18535.0,18581.0,19143.0,19101.0,19062.0,18204.0,X
64,2018,DE,19342,18770,19187,19171.0,19558.0,20086.0,21254.0,22888.0,...,16895.0,17604.0,16842.0,17785.0,18091.0,18342.0,17943.0,18990.0,17954.0,X
80,2017,DE,20918,22070,21236,22083.0,23640.0,22744.0,22683.0,22266.0,...,16762.0,17371.0,17594.0,17676.0,17877.0,18295.0,18504.0,18500.0,18652.0,X
96,2016,DE,18467,18439,18627,18707.0,18493.0,18541.0,18483.0,18475.0,...,17580.0,17782.0,18591.0,17911.0,18146.0,18793.0,18885.0,19376.0,19744.0,X

In [10]:
sterbefaelleInsg=sterbefaelleInsg.append(sterbefaelleDInsg)

In [11]:
sterbefaelleInsg["weekNr"] = sterbefaelleInsg["Unnamed: 2"] + sterbefaelleInsg["Unnamed: 1"].astype(str)

In [12]:
sterbefaelleInsg

,Unnamed: 1,Unnamed: 2,1,2,3,4,5,6,7,8,...,45,46,47,48,49,50,51,52,53,weekNr
0,2021,SH,804,794,850,826.0,778.0,797.0,819.0,677.0,...,705.0,700.0,732.0,770.0,832.0,728.0,786.0,782.0,X,SH2021
5,2021,HH,451,437,463,396.0,416.0,363.0,405.0,347.0,...,370.0,378.0,389.0,396.0,400.0,332.0,369.0,400.0,X,HH2021
10,2021,NI,2164,2092,2167,2165.0,2179.0,2133.0,2061.0,1946.0,...,2049.0,2142.0,2081.0,2163.0,2187.0,2113.0,2055.0,2117.0,X,NI2021
15,2021,HB,181,158,156,148.0,183.0,166.0,165.0,159.0,...,148.0,185.0,175.0,172.0,173.0,166.0,190.0,195.0,X,HB2021
20,2021,NW,4879,5006,4941,4753.0,4551.0,4443.0,4411.0,4192.0,...,4274.0,4526.0,4621.0,5009.0,4958.0,4725.0,4767.0,4616.0,X,NW2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,2020,DE,18883,19408,18953,18827.0,19774.0,19038.0,19648.0,18953.0,...,19007.0,19727.0,20182.0,21304.0,22604.0,24003.0,24724.0,25554.0,25497,DE2020
48,2019,DE,18686,19170,19163,19505.0,19812.0,19981.0,20150.0,20349.0,...,17859.0,18242.0,18535.0,18581.0,19143.0,19101.0,19062.0,18204.0,X,DE2019
64,2018,DE,19342,18770,19187,19171.0,19558.0,20086.0,21254.0,22888.0,...,17604.0,16842.0,17785.0,18091.0,18342.0,17943.0,18990.0,17954.0,X,DE2018
80,2017,DE,20918,22070,21236,22083.0,23640.0,22744.0,22683.0,22266.0,...,17371.0,17594.0,17676.0,17877.0,18295.0,18504.0,18500.0,18652.0,X,DE2017
96,2016,DE,18467,18439,18627,18707.0,18493.0,18541.0,18483.0,18475.0,...,17782.0,18591.0,17911.0,18146.0,18793.0,18885.0,19376.0,19744.0,X,DE2016

In [13]:
# transpose output for d3js usage, create useful column names
output = sterbefaelleInsg.drop(columns=["Unnamed: 2","Unnamed: 1"]).set_index("weekNr").T

In [14]:
output

weekNr,SH2021,HH2021,NI2021,HB2021,NW2021,HE2021,RP2021,BW2021,BY2021,SL2021,...,SN2016,ST2016,TH2016,DE2022,DE2021,DE2020,DE2019,DE2018,DE2017,DE2016
1,804,451,2164,181,4879,1861,1177,2772,3612,355,...,1034,658,568,20430,24844,18883,18686,19342,20918,18467
2,794,437,2092,158,5006,1807,1223,2773,3599,298,...,1059,650,551,19532,24501,19408,19170,18770,22070,18439
3,850,463,2167,156,4941,1739,1212,2751,3440,333,...,1123,616,593,19537,24077,18953,19163,19187,21236,18627
4,826,396,2165,148,4753,1679,1120,2533,3195,274,...,1166,601,624,NaN,22645,18827,19505,19171,22083,18707
5,778,416,2179,183,4551,1539,1024,2381,3061,318,...,1114,635,617,NaN,21736,19774,19812,19558,23640,18493
6,797,363,2133,166,4443,1505,995,2290,2903,301,...,1097,601,546,NaN,20932,19038,19981,20086,22744,18541
7,819,405,2061,165,4411,1499,966,2241,2917,322,...,1053,627,629,NaN,20469,19648,20150,21254,22683,18483
8,677,347,1946,159,4192,1366,889,2124,2586,298,...,1104,700,611,NaN,18950,18953,20349,22888,22266,18475
9,675,353,1827,155,4080,1303,863,2087,2558,251,...,1087,672,563,NaN,18437,19505,20790,25535,20930,18926
10,714,362,1884,145,4034,1324,878,2057,2694,245,...,1098,653,629,NaN,18607,19667,20453,26777,19102,18888
11,735,326,1907,155,3855,1292,939,2033,2669,247,...,1084,676,604,NaN,18335,19849,19795,24385,18665,18971
12,653,333,1779,169,4066,1316,858,2129,2635,243,...,1082,703,550,NaN,18391,19722,19016,22777,17640,18826
13,670,338,1797,136,3996,1313,905,2067,2730,267,...,1079,655,549,NaN,18493,19678,18562,20906,17731,18617
14,677,310,1846,167,4071,1326,917,2237,2595,231,...,1067,627,575,NaN,18820,20662,18671,20038,17028,18244
15,706,346,1818,167,4150,1390,937,2189,2662,268,...,1045,599,536,NaN,19062,20502,17852,19165,16901,17712
16,696,357,1872,155,4201,1338,938,2187,2774,238,...,991,584,503,NaN,19241,19261,18089,17992,16637,16775
17,674,341,1883,172,4197,1418,961,2336,2778,247,...,985,627,518,NaN,19507,18557,17894,17093,17634,17053
18,710,353,1896,150,4322,1374,975,2209,2732,265,...,1005,604,549,NaN,19308,17920,17090,16789,17129,16901
19,641,334,1790,135,4127,1311,891,2180,2643,250,...,1014,659,503,NaN,18589,17651,17118,17226,17343,17629
20,665,316,1766,145,3884,1250,884,2109,2515,250,...,970,565,522,NaN,17787,17001,17315,16488,17079,16601
21,687,321,1721,128,3760,1202,875,2017,2435,217,...,963,598,507,NaN,17158,17163,17080,16513,16451,16286
22,664,361,1934,154,3906,1289,910,2157,2491,266,...,905,572,555,NaN,18162,16776,16921,17039,16902,16346
23,641,362,1744,151,3840,1241,797,2071,2372,272,...,890,509,482,NaN,17408,17262,17491,16714,15846,15799
24,738,384,1967,134,4233,1369,1007,2232,2577,289,...,898,520,483,NaN,19043,16601,16484,15582,16087,15717
25,606,318,1685,148,3796,1197,828,2017,2504,217,...,989,640,533,NaN,17179,16401,16639,15843,16819,16910
26,649,361,1708,153,3773,1218,851,1935,2365,227,...,944,542,495,NaN,16983,17293,17918,16569,16076,15699
27,641,292,1758,164,3728,1152,851,1977,2456,239,...,948,566,477,NaN,16949,16457,16552,16622,16424,16229
28,664,343,1783,140,3866,1283,1029,1991,2381,232,...,947,578,502,NaN,17616,16142,16319,16070,15603,16172
29,603,336,1755,138,3826,1321,936,2140,2516,256,...,971,603,470,NaN,17571,16537,16856,16702,16589,16985
30,654,352,1756,130,3758,1216,867,1994,2475,234,...,1040,599,503,NaN,17199,16887,19630,18340,16058,16157
31,658,336,1709,131,3769,1171,866,1942,2412,235,...,886,554,449,NaN,16987,17433,17034,20371,16494,15439
32,660,341,1795,172,3827,1196,986,2025,2543,250,...,918,498,462,NaN,17527,17470,16540,18478,15784,15487
33,647,333,1738,146,3862,1225,880,2049,2482,264,...,899,524,501,NaN,17436,19720,15934,16890,16148,16258
34,653,350,1775,148,3820,1197,831,2024,2369,256,...,978,598,533,NaN,17150,17559,16263,16612,15880,17147
35,613,358,1764,129,3839,1258,888,2007,2480,251,...,978,580,450,NaN,17324,16656,17637,16000,16064,16101
36,682,378,1945,162,4241,1297,958,2162,2717,283,...,954,563,526,NaN,18811,16789,15988,16390,15706,16116
37,639,369,1842,156,3973,1282,913,2128,2545,252,...,975,551,516,NaN,17999,17155,16303,16292,16146,16372
38,663,317,1855,127,4017,1251,922,2160,2584,256,...,895,512,509,NaN,18087,17555,16500,16651,16505,15606
39,679,359,1807,168,3959,1268,931,2085,2623,233,...,970,574,504,NaN,18059,17446,17402,15969,16747,16336
40,688,336,1808,152,3990,1285,976,2132,2654,272,...,989,548,510,NaN,18137,17614,16899,16622,16664,16352
41,698,319,1832,141,4059,1263,964,2323,2790,279,...,981,578,511,NaN,18861,17501,17666,16993,17470,17427
42,709,350,1926,153,4195,1386,946,2410,2914,277,...,961,603,589,NaN,19704,17754,17713,16552,17139,17599
43,768,376,1983,144,4325,1349,991,2468,2981,295,...,1065,564,521,NaN,20183,18588,17327,16608,17059,17586
44,711,371,1931,150,4294,1456,985,2408,3079,266,...,993,552,571,NaN,20226,18584,17488,16895,16762,17580
45,705,370,2049,148,4274,1468,1069,2464,3322,306,...,1079,607,550,NaN,20930,19007,17859,17604,17371,17782
46,700,378,2142,185,4526,1590,1019,2616,3443,326,...,1084,628,541,NaN,22144,19727,18242,16842,17594,18591
47,732,389,2081,175,4621,1576,1073,2749,3688,328,...,1037,598,579,NaN,23042,20182,18535,17785,17676,17911
48,770,396,2163,172,5009,1628,1129,2808,3713,307,...,1030,651,614,NaN,23968,21304,18581,18091,17877,18146
49,832,400,2187,173,4958,1552,1064,2790,3560,343,...,1118,603,588,NaN,23755,22604,19143,18342,18295,18793
50,728,332,2113,166,4725,1531,1118,2717,3306,310,...,1158,629,599,NaN,22685,24003,19101,17943,18504,18885
51,786,369,2055,190,4767,1491,1098,2651,3242,325,...,1137,680,618,NaN,22272,24724,19062,18990,18500,19376
52,782,400,2117,195,4616,1457,1082,2556,3041,324,...,1219,661,603,NaN,21856,25554,18204,17954,18652,19744
53,X,X,X,X,X,X,X,X,X,X,...,X,X,X,NaN,X,25497,X,X,X,X

In [15]:
# save as csv for use in a d3js graph, you may want to archive this by date
output.to_csv("overall_mortality_weekly_germany_states.csv",index_label="weekNr",float_format='%.0f')